language: node_js
node_js:
  - 0.10
before_script: mkdir -p shippable/codecoverage && mkdir -p shippable/testresults
after_script:
  - ./node_modules/.bin/mocha -R xunit ./tests > shippable/testresults/result.xml
  - ./node_modules/.bin/istanbul cover ./node_modules/.bin/mocha tests
  - ./node_modules/.bin/istanbul report cobertura --dir shippable/codecoverage/
